kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins-data-pv
  labels:
    type: local
spec:
  storageClassName: generic
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/jenkins"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-data-pvc
spec:
  storageClassName: generic
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
